[package]
name = "gm_fsdialog"
authors = ["Earu"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gmod = { version = "*", default-features = false, features = ["gmcl"] }
rfd = "0.7.0"
futures = "0.3.21"